#!/usr/bin/env python3
"""loading.py - data analysis and dependency management.

Checks the availability of numpy, pandas, and matplotlib. The program
explains how to install missing dependencies with pip or Poetry and,
when everything is installed, generates Matrix data with numpy,
analyses it with pandas, and produces a chart with matplotlib.
"""

import sys
from typing import Any


DEPENDENCIES: dict[str, str] = {
    "pandas": "Data manipulation ready",
    "numpy": "Numerical computation ready",
    "matplotlib": "Visualization ready",
}

DATA_FILE = "matrix_data.csv"
CHART_FILE = "matrix_analysis.png"


def installed_version(package: str) -> str:
    """Return the installed version of a package, or 'missing'."""
    try:
        module = __import__(package)
    except ImportError:
        return "missing"

    return str(getattr(module, "__version__", "unknown"))


def check_dependencies() -> dict[str, bool]:
    """Return which required dependencies are available."""
    status: dict[str, bool] = {}

    for name in DEPENDENCIES:
        status[name] = installed_version(name) != "missing"

    return status


def show_dependency_status(status: dict[str, bool]) -> None:
    """Print the availability state of every dependency."""
    print("Checking dependencies:")

    for name in sorted(DEPENDENCIES):
        purpose = DEPENDENCIES[name]
        version = installed_version(name)

        if status[name]:
            print(
                "  [OK] {} ({}) - {}".format(
                    name,
                    version,
                    purpose,
                )
            )
        else:
            print("  [MISSING] {} - {}".format(name, purpose))


def show_install_instructions() -> None:
    """Print installation instructions for pip and Poetry."""
    print()
    print("Install dependencies with pip:")
    print("  $ pip install -r requirements.txt")

    print()
    print("Or with Poetry:")
    print("  $ poetry install")

    print()
    print("Then run this program again.")


def show_manager_comparison() -> None:
    """Demonstrate pip and Poetry dependency management."""
    print()
    print("Dependency management comparison:")

    print()
    print("pip:")
    print("  Configuration file: requirements.txt")
    print("  Install command: pip install -r requirements.txt")
    print("  Purpose: install the packages listed in the file.")
    print("  Environment: usually managed separately with venv.")

    print()
    print("Poetry:")
    print("  Configuration file: pyproject.toml")
    print("  Install command: poetry install")
    print("  Purpose: manage dependencies and project metadata.")
    print("  Environment: Poetry can manage the project environment.")
    print("  Lock file: poetry.lock, generated by Poetry.")


def generate_and_export_data() -> None:
    """Generate synthetic Matrix data and save it to a CSV file."""
    import numpy as np

    rng = np.random.default_rng(42)
    size = 1000

    metric = {
        "signal": rng.normal(50.0, 15.0, size),
        "noise": rng.normal(0.0, 5.0, size),
        "time": rng.uniform(0.0, 100.0, size),
    }

    rows = sorted(
        zip(
            metric["time"],
            metric["signal"],
            metric["noise"],
        )
    )

    try:
        with open(DATA_FILE, "w", encoding="utf-8") as output:
            output.write("time,signal,noise\n")

            for time_value, signal_value, noise_value in rows:
                output.write(
                    "{},{},{}\n".format(
                        time_value,
                        signal_value,
                        noise_value,
                    )
                )
    except UnicodeError as error:
        raise RuntimeError(
            "Could not encode the generated data as UTF-8"
        ) from error
    except OSError as error:
        raise RuntimeError(
            "Could not write data to {}".format(DATA_FILE)
        ) from error


def build_dataframe() -> Any:
    """Load the generated CSV into a pandas DataFrame."""
    import pandas as pd  # type: ignore[import-untyped]

    try:
        return pd.read_csv(DATA_FILE)
    except (OSError, UnicodeError, ValueError) as error:
        raise RuntimeError(
            "Could not read data from {}".format(DATA_FILE)
        ) from error


def analyze_dataframe(frame: Any) -> Any:
    """Return a statistical summary of the DataFrame."""
    return frame.describe()


def render_plot(frame: Any) -> str:
    """Plot the data and save the visualization to a PNG file."""
    import matplotlib

    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

    ordered_frame = frame.sort_values("time")

    figure, axes = plt.subplots()
    axes.plot(
        ordered_frame["time"],
        ordered_frame["signal"],
        linewidth=0.5,
    )
    axes.set_title("Matrix signal over time")
    axes.set_xlabel("time")
    axes.set_ylabel("signal")

    figure.tight_layout()
    figure.savefig(CHART_FILE, dpi=200)
    plt.close(figure)

    return CHART_FILE


def run_analysis() -> None:
    """Perform the NumPy, pandas, and Matplotlib analysis pipeline."""
    print()
    print("Analyzing Matrix data...")

    generate_and_export_data()
    frame = build_dataframe()
    summary = analyze_dataframe(frame)

    print("Processing 1000 data points...")
    print(summary)

    print("Generating visualization...")
    chart = render_plot(frame)

    print()
    print("Analysis complete!")
    print("Data saved to: {}".format(DATA_FILE))
    print("Results saved to: {}".format(chart))


def show_versions() -> None:
    """Print the installed version of each dependency."""
    print("Installed versions:")

    for name in sorted(DEPENDENCIES):
        print("  {}: {}".format(name, installed_version(name)))


def main() -> None:
    """Drive the analysis or explain how to install dependencies."""
    print("LOADING STATUS: Loading programs...")

    status = check_dependencies()
    show_dependency_status(status)

    missing = [
        name for name in DEPENDENCIES
        if not status[name]
    ]

    show_manager_comparison()

    if missing:
        show_install_instructions()
        sys.exit(1)

    show_versions()
    run_analysis()


if __name__ == "__main__":
    main()
